
version: "3"

volumes:
  pg_data:

services:
    postgres:
        container_name: postgres
        image: postgres:latest
        ports:
            - 5432:5432
        volumes:
            - pg_data:/var/lib/postgresql/data/
        env_file:
            - .env      