"""empty message

Revision ID: 324c2b281378
Revises: c9b28db1321e
Create Date: 2020-10-02 16:35:04.744042

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from application.models import *
from application.tracker.models import *



# revision identifiers, used by Alembic.
revision = '324c2b281378'
down_revision = 'c9b28db1321e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('geo_polled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petition', 'geo_polled_at')
    # ### end Alembic commands ###
