"""empty message

Revision ID: 4309b1546d1d
Revises: dee0ef42f3ca
Create Date: 2020-09-27 14:42:16.605717

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from application.models import *
from application.tracker.models import *



# revision identifiers, used by Alembic.
revision = '4309b1546d1d'
down_revision = 'dee0ef42f3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_signatures_by_constituency_ons_code'), 'signatures_by_constituency', ['ons_code'], unique=False)
    op.create_index(op.f('ix_signatures_by_country_iso_code'), 'signatures_by_country', ['iso_code'], unique=False)
    op.create_index(op.f('ix_signatures_by_region_ons_code'), 'signatures_by_region', ['ons_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatures_by_region_ons_code'), table_name='signatures_by_region')
    op.drop_index(op.f('ix_signatures_by_country_iso_code'), table_name='signatures_by_country')
    op.drop_index(op.f('ix_signatures_by_constituency_ons_code'), table_name='signatures_by_constituency')
    # ### end Alembic commands ###
