"""empty message

Revision ID: 44e4ef3e738c
Revises: 9f49fc8c8958
Create Date: 2020-09-30 15:37:23.585392

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from application.models import *
from application.tracker.models import *



# revision identifiers, used by Alembic.
revision = '44e4ef3e738c'
down_revision = '9f49fc8c8958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('trend_pos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petition', 'trend_pos')
    # ### end Alembic commands ###
