"""empty message

Revision ID: 4a10fe959a7f
Revises: 828f8b15585f
Create Date: 2020-09-08 14:09:35.240608

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from application.models import *
from application.tracker.models import *



# revision identifiers, used by Alembic.
revision = '4a10fe959a7f'
down_revision = '828f8b15585f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('creator_name', sa.String(), nullable=True))
    op.add_column('petition', sa.Column('debate_outcome_at', sa.DateTime(), nullable=True))
    op.add_column('petition', sa.Column('debate_threshold_reached_at', sa.DateTime(), nullable=True))
    op.add_column('petition', sa.Column('government_response_at', sa.DateTime(), nullable=True))
    op.add_column('petition', sa.Column('moderation_threshold_reached_at', sa.DateTime(), nullable=True))
    op.add_column('petition', sa.Column('response_threshold_reached_at', sa.DateTime(), nullable=True))
    op.add_column('petition', sa.Column('scheduled_debate_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('petition', 'scheduled_debate_date')
    op.drop_column('petition', 'response_threshold_reached_at')
    op.drop_column('petition', 'moderation_threshold_reached_at')
    op.drop_column('petition', 'government_response_at')
    op.drop_column('petition', 'debate_threshold_reached_at')
    op.drop_column('petition', 'debate_outcome_at')
    op.drop_column('petition', 'creator_name')
    # ### end Alembic commands ###
