"""empty message

Revision ID: 77ff383eaf62
Revises: c6a0fa518f82
Create Date: 2020-07-14 14:52:29.475607

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from PetitionTracker.tracker.models import *



# revision identifiers, used by Alembic.
revision = '77ff383eaf62'
down_revision = 'c6a0fa518f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('db_created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'db_created_at')
    # ### end Alembic commands ###
