"""empty message

Revision ID: 7812245fd360
Revises: 722cb98d4464
Create Date: 2020-12-11 16:05:23.541736

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from application.models import *
from application.tracker.models import *



# revision identifiers, used by Alembic.
revision = '7812245fd360'
down_revision = '722cb98d4464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('trend_index', sa.Integer(), nullable=True))
    op.drop_column('petition', 'trend_position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('petition', sa.Column('trend_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('petition', 'trend_index')
    # ### end Alembic commands ###
