"""empty message

Revision ID: 9c2154fff738
Revises: e3e2ea9b8579
Create Date: 2020-10-10 14:15:36.292940

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from application.models import *
from application.tracker.models import *



# revision identifiers, used by Alembic.
revision = '9c2154fff738'
down_revision = 'e3e2ea9b8579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_run', sa.Column('retries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_run', 'retries')
    # ### end Alembic commands ###
