"""empty message

Revision ID: 9f49fc8c8958
Revises: dee0ef42f3ca
Create Date: 2020-09-29 14:03:24.508162

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from application.models import *
from application.tracker.models import *



# revision identifiers, used by Alembic.
revision = '9f49fc8c8958'
down_revision = 'dee0ef42f3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_record_petition_id'), 'record', ['petition_id'], unique=False)
    op.create_index(op.f('ix_record_timestamp'), 'record', ['timestamp'], unique=False)
    op.create_index(op.f('ix_signatures_by_constituency_ons_code'), 'signatures_by_constituency', ['ons_code'], unique=False)
    op.create_index(op.f('ix_signatures_by_constituency_record_id'), 'signatures_by_constituency', ['record_id'], unique=False)
    op.create_index(op.f('ix_signatures_by_country_iso_code'), 'signatures_by_country', ['iso_code'], unique=False)
    op.create_index(op.f('ix_signatures_by_country_record_id'), 'signatures_by_country', ['record_id'], unique=False)
    op.create_index(op.f('ix_signatures_by_region_ons_code'), 'signatures_by_region', ['ons_code'], unique=False)
    op.create_index(op.f('ix_signatures_by_region_record_id'), 'signatures_by_region', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signatures_by_region_record_id'), table_name='signatures_by_region')
    op.drop_index(op.f('ix_signatures_by_region_ons_code'), table_name='signatures_by_region')
    op.drop_index(op.f('ix_signatures_by_country_record_id'), table_name='signatures_by_country')
    op.drop_index(op.f('ix_signatures_by_country_iso_code'), table_name='signatures_by_country')
    op.drop_index(op.f('ix_signatures_by_constituency_record_id'), table_name='signatures_by_constituency')
    op.drop_index(op.f('ix_signatures_by_constituency_ons_code'), table_name='signatures_by_constituency')
    op.drop_index(op.f('ix_record_timestamp'), table_name='record')
    op.drop_index(op.f('ix_record_petition_id'), table_name='record')
    # ### end Alembic commands ###
