"""empty message

Revision ID: bf7ada70e567
Revises: 718fa0099b10
Create Date: 2020-10-16 14:36:46.570095

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from application.models import *
from application.tracker.models import *



# revision identifiers, used by Alembic.
revision = 'bf7ada70e567'
down_revision = '718fa0099b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('record_petition_id_fkey', 'record', type_='foreignkey')
    op.create_foreign_key(None, 'record', 'petition', ['petition_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('signatures_by_constituency_record_id_fkey', 'signatures_by_constituency', type_='foreignkey')
    op.create_foreign_key(None, 'signatures_by_constituency', 'record', ['record_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('signatures_by_country_record_id_fkey', 'signatures_by_country', type_='foreignkey')
    op.create_foreign_key(None, 'signatures_by_country', 'record', ['record_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('signatures_by_region_record_id_fkey', 'signatures_by_region', type_='foreignkey')
    op.create_foreign_key(None, 'signatures_by_region', 'record', ['record_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.create_foreign_key('record_petition_id_fkey', 'record', 'petition', ['petition_id'], ['id'])
    op.drop_constraint(None, 'signatures_by_region', type_='foreignkey')
    op.create_foreign_key('signatures_by_region_record_id_fkey', 'signatures_by_region', 'record', ['record_id'], ['id'])
    op.drop_constraint(None, 'signatures_by_country', type_='foreignkey')
    op.create_foreign_key('signatures_by_country_record_id_fkey', 'signatures_by_country', 'record', ['record_id'], ['id'])
    op.drop_constraint(None, 'signatures_by_constituency', type_='foreignkey')
    op.create_foreign_key('signatures_by_constituency_record_id_fkey', 'signatures_by_constituency', 'record', ['record_id'], ['id'])
    # ### end Alembic commands ###
