"""empty message

Revision ID: d7cdfd83d07b
Revises: b9619b132046
Create Date: 2020-07-18 18:35:19.577129

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from PetitionTracker.models import *
from PetitionTracker.tracker.models import *



# revision identifiers, used by Alembic.
revision = 'd7cdfd83d07b'
down_revision = 'b9619b132046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('meta', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'meta')
    # ### end Alembic commands ###
