"""empty message

Revision ID: e3e2ea9b8579
Revises: 5c2c48355ad6
Create Date: 2020-10-09 17:50:26.519862

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from application.models import *
from application.tracker.models import *

import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'e3e2ea9b8579'
down_revision = '5c2c48355ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('run_on_startup', sa.Boolean(), nullable=False))
    op.add_column('task_run', sa.Column('celery_id', sa.String(), nullable=False))
    op.add_column('task_run', sa.Column('periodic', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_run', 'periodic')
    op.drop_column('task_run', 'celery_id')
    op.drop_column('task', 'run_on_startup')
    # ### end Alembic commands ###
