"""empty message

Revision ID: e45733f9c679
Revises: 5c2c48355ad6
Create Date: 2020-10-05 21:30:23.893087

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from application.models import *
from application.tracker.models import *

from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'e45733f9c679'
down_revision = '5c2c48355ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sqlalchemy_utils.types.choice.ChoiceType([('I', 'INFO'), ('D', 'DEBUG'), ('W', 'WARN'), ('E', 'ERROR'), ('F', 'FATAL')]), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_run_id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_log_app'), 'base_log', ['app'], unique=False)
    op.create_index(op.f('ix_base_log_module'), 'base_log', ['module'], unique=False)
    op.create_index(op.f('ix_base_log_task_id'), 'base_log', ['task_id'], unique=False)
    op.create_index(op.f('ix_base_log_task_run_id'), 'base_log', ['task_run_id'], unique=False)
    op.drop_index('ix_task_log_task_id', table_name='task_log')
    op.drop_index('ix_task_log_task_run_id', table_name='task_log')
    op.drop_table('task_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_run_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='task_log_task_id_fkey'),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_run.id'], name='task_log_task_run_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_log_pkey')
    )
    op.create_index('ix_task_log_task_run_id', 'task_log', ['task_run_id'], unique=False)
    op.create_index('ix_task_log_task_id', 'task_log', ['task_id'], unique=False)
    op.drop_index(op.f('ix_base_log_task_run_id'), table_name='base_log')
    op.drop_index(op.f('ix_base_log_task_id'), table_name='base_log')
    op.drop_index(op.f('ix_base_log_module'), table_name='base_log')
    op.drop_index(op.f('ix_base_log_app'), table_name='base_log')
    op.drop_table('base_log')
    # ### end Alembic commands ###
